apiVersion: v1
kind: Service
metadata:
  name: ollama-gpt-server
spec:
  selector:
    app.kubernetes.io/name: ollama-gpt-server
  ports:
    - name: grpc
      port: 50053
      targetPort: grpc
      appProtocol: grpc
