apiVersion: v1
kind: Service
metadata:
  name: chroma-db-headless
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: chroma-db
  ports:
    - name: http
      port: 8000
      targetPort: http
