apiVersion: v1
kind: Service
metadata:
  name: orchestrator-server
spec:
  selector:
    app.kubernetes.io/name: orchestrator-server
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
      appProtocol: grpc
