apiVersion: v1
kind: Service
metadata:
  name: rag-server
spec:
  selector:
    app.kubernetes.io/name: rag-server
  ports:
    - name: grpc
      port: 50052
      targetPort: grpc
      appProtocol: grpc
